name: Robert Marks
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27282c'
    - '#f7d1c8'
    - '#bb4555'
    - '#3b523e'
    - '#be715e'
  brandStrength: 0.1875
  lightness: 0.045643092365935445
  saturation: 0.875
  rhythmicContrast: 0.22561914450488985
purpose: []
